name: Debug workflow

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Change directory
        run: cd ./.github/actions/hello-world/

      - name: Install dependencies
        run: npm install

      - name: Run ls
        run: ls

      - name: Run debug 1
        run: node debug1.js

      - name: Run debug 2
        run: node debug2.js

      - name: Hello world action step
        uses: ./.github/actions/hello-world/
        id: hello
        with:
          who-to-greet: 'Mona the Octocat'

      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
