name: Increment Counter

on:
  push: {}
  schedule:
    - cron: '* * * * *'

jobs:
  inc_counter:
    runs-on: [ubuntu-latest]
    steps:
    - name: do checkout
      uses: actions/checkout@v1
      with:
        ref: master
    - name: increment counter
      run: echo $(($(cat counter) + 1)) > counter
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
